### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Kobzol** [Kobzol/memviz#3]
Below are a few things (in no particular order of importance) that should be improved in the extension, I plan to work on these over the upcoming weeks. I'm lazy, so I put them all inside one issue :) I will separate them into sub-issues as needed.

- [ ] Add some configuration
  - A "turn off" button
  - A checkbox that controls whether heap allocations should be tracked
  - Configuration could be in a foldable panel, e.g. as in https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample
- [ ] On-demand loading
  - Nested values (e.g. the field of a struct that is a field of a struct that is an element of an array) should be only loaded on-demand, after the user clicks on them.
  - It would be nice to create some renderless Vue component to handle this universally (or include the logic inside `Value`).
- [ ] Fix overlapping tooltips
  - The [Tippy](https://vue-tippy.netlify.app/) tooltips can overlap when multiple nested DOM elements have such a tooltip. It would be nice to only show the top-most element.
- [ ] Visualize strings
- [ ] Re-enable pointer array visualization
- [ ] Make stack frames a pointer target
- [ ] Handle request errors
  - Currently, requests between the webview and the extension are assumed to always succeed. That does not always happen though :)
- [ ] Visualize structures
- [ ] Add stepping buttons
  - Same as in the VSCode debugger, `continue`, `step over`, `step in`, `step out`, `pause` etc.
- [ ] Improve styling of data types
  - Common primitive data types (e.g. ints and floats) could be rendered with some badge, to reduce the space of `int`
- [ ] Visualize heap allocations
  - Heap allocations are already being tracked, but they are not visualized 
  - [ ] Reset heap on process start
- [ ] Visualize global variables

**Comment by rababR1** [comment]
How about support for Windows? I came across this and I found it very useful so I can visualize C/C++ programs, but its for Linux...
:(

**Comment by Kobzol** [comment]
I'm doing a few Linux specific things, but these could be skipped. I'm also doing *a lot* of GDB specific things though, that's not possible to remove without rewriting half of the extension. Could you use the extension with GDB, e.g. through mingw?

Btw, the extension already works on WSL.

**Comment by rababR1** [comment]
Sadly, no. I don't plan to use WSL, but I have MingGW:
![image](https://github.com/user-attachments/assets/430e732c-92f4-4d53-9d46-41b7a62b4404)

**Comment by Kobzol** [comment]
I moved the discussion into a separate issue: https://github.com/Kobzol/memviz/issues/17.
